version: '3.4'

x-env:
  environment: &env
    NODES_URLS: "http://node1:8000,http://node2:8000,http://node3:8000"
    NODE_PORT: "8000"
    REQUEST_TIMEOUT_MILLISECONDS: "100"
    HEARTBEAT_PERIOD_MILLISECONDS: "50"
    ELECTION_TIMEOUT_MILLISECONDS: "150"

services:
  node1:
    build:
      context: ../
      dockerfile: build/Dockerfile
    networks:
      - isolated_network
    environment:
      <<: *env
      NODE_INDEX: "0"

  node2:
    build:
      context: ../
      dockerfile: build/Dockerfile
    networks:
      - isolated_network
    environment:
      <<: *env
      NODE_INDEX: "1"

  node3:
    build:
      context: ../
      dockerfile: build/Dockerfile
    networks:
      - isolated_network
    environment:
      <<: *env
      NODE_INDEX: "2"


networks:
  isolated_network:
    driver: bridge